#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email.DiscoPlugin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Models.Repository;
    using Disco.Services.Plugins;
    using Disco.Services.Web;
    
    #line 1 "..\..\Views\Configuration.cshtml"
    using Email.DiscoPlugin.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Configuration.cshtml")]
    public partial class Configuration : Disco.Services.Plugins.PluginWebViewPage<ConfigurationModel>
    {
        public Configuration()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" style=\"width: 750px; margin: 0 auto 0 auto;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form\"");

WriteLiteral(" style=\"float: left\"");

WriteLiteral(">\r\n        <h2>Email Server Configuration</h2>\r\n        <table>\r\n            <tr>" +
"\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 10 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.SmtpServerAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 13 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpServerAddress));

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpServerAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n");

WriteLiteral("                    ");

            
            #line 19 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.SmtpServerPort));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpServerPort));

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n                    <span>Default is 25</span>\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpServerPort));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.EnableSsl));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Configuration.cshtml"
               Write(Html.CheckBoxFor(m => m.EnableSsl));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.SmtpSenderAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpSenderAddress));

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpSenderAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.AuthenticationRequried));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Views\Configuration.cshtml"
               Write(Html.CheckBoxFor(m => m.AuthenticationRequried));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.SmtpUsername));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 57 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpUsername));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 58 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpUsername));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Views\Configuration.cshtml"
               Write(Html.DisplayNameFor(m => m.SmtpPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 66 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpPassword));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 67 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n        </table>\r\n        <hr/>\r\n    " +
"    <h2>Email Alert Configurations</h2>\r\n        <table>\r\n");

            
            #line 74 "..\..\Views\Configuration.cshtml"
            
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Configuration.cshtml"
             for (var i = 0; i < Model.MessageConfig.Count; i++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <th>");

            
            #line 77 "..\..\Views\Configuration.cshtml"
                   Write(Html.DisplayNameFor(m => Model.MessageConfig[i].EmailMessageType));

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 77 "..\..\Views\Configuration.cshtml"
                                                                                       Write(Model.MessageConfig[i].EmailMessageType.GetDisplayName());

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 77 "..\..\Views\Configuration.cshtml"
                                                                                                                                                 Write(Html.HiddenFor(m => m.MessageConfig[i].EmailMessageType));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 79 "..\..\Views\Configuration.cshtml"
                   Write(Html.DisplayNameFor(m => Model.MessageConfig[i].EmailSubject));

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 79 "..\..\Views\Configuration.cshtml"
                                                                                   Write(Html.EditorFor(m => Model.MessageConfig[i].EmailSubject, new { @class = "resizer" }));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                        ");

            
            #line 80 "..\..\Views\Configuration.cshtml"
                   Write(Html.DisplayNameFor(m => Model.MessageConfig[i].EmailBody));

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 80 "..\..\Views\Configuration.cshtml"
                                                                                Write(Html.EditorFor(m => Model.MessageConfig[i].EmailBody, new { @class = "resizer" }));

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n");

            
            #line 81 "..\..\Views\Configuration.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Configuration.cshtml"
                         if (Model.MessageConfig[i].EmailMessageType != MessageType.PluginTestEmail)
                        {
                            
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Configuration.cshtml"
                       Write(Html.DisplayNameFor(m => Model.MessageConfig[i].EmailAlertEnabled));

            
            #line default
            #line hidden
WriteLiteral(":");

WriteLiteral(" ");

            
            #line 83 "..\..\Views\Configuration.cshtml"
                                                                                                              
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Configuration.cshtml"
                                                                                                         Write(Html.CheckBoxFor(m => Model.MessageConfig[i].EmailAlertEnabled));

            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Configuration.cshtml"
                                                                                                                                                                              
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");

            
            #line 87 "..\..\Views\Configuration.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </table>
    </div>
</div>
<script>
    $(document).ready(function ()
    {
        $('[value=""Save Configuration""]').val('Save & Test Configuration');

        if ($('#AuthenticationRequried').not(':checked'))
        {
            $('#SmtpUsername').val("""");
            $('#SmtpPassword').val("""");
            $('#SmtpUsername').prop(""disabled"", !$(this).is(':checked'));
            $('#SmtpPassword').prop(""disabled"", !$(this).is(':checked'));
        }

        $('#AuthenticationRequried').change(function () {
            $('#SmtpUsername').val("""");
            $('#SmtpPassword').val("""");
            $('#SmtpUsername').prop(""disabled"", !$(this).is(':checked'));
            $('#SmtpPassword').prop(""disabled"", !$(this).is(':checked'));
        });
    });
</script>");

        }
    }
}
#pragma warning restore 1591
