#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email.DiscoPlugin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Models.Repository;
    using Disco.Services.Plugins;
    using Disco.Services.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Configuration.cshtml")]
    public partial class Configuration : Disco.Services.Plugins.PluginWebViewPage<Email.DiscoPlugin.Models.ConfigurationModel>
    {
        public Configuration()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" style=\"width: 750px; margin: 0 auto 0 auto;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form\"");

WriteLiteral(" style=\"float: left\"");

WriteLiteral(">\r\n        <h2>\r\n            Email Server Configuration Details\r\n        </h2>\r\n " +
"       <table>\r\n            <tr>\r\n                <th>\r\n                    SMTP" +
" Mail Server Address:\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpServerAddress));

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpServerAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n                    SMTP Sender Address:\r\n                </th>\r\n            " +
"    <td>\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpSenderAddress));

            
            #line default
            #line hidden
WriteLiteral("<br/>\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpSenderAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n                    Authentication Required:\r\n                </th>\r\n        " +
"        <td>\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Configuration.cshtml"
               Write(Html.CheckBoxFor(m => m.AuthenticationRequried));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.AuthenticationRequried));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n                    SMTP Username:\r\n                </th>\r\n                <t" +
"d>\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpUsername));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpUsername));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
">\r\n                    SMTP Password:\r\n                </th>\r\n                <t" +
"d>\r\n");

WriteLiteral("                    ");

            
            #line 50 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.SmtpPassword));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.SmtpPassword));

            
            #line default
            #line hidden
WriteLiteral(@"
                </td>
            </tr>
        </table>
        <hr />
        <h2>
            Email Alert Configuration
        </h2>
        <table>
            <tr>
                <th>
                    Send emails when device is ready for collection:
                </th>
                <td>
");

WriteLiteral("                    ");

            
            #line 65 "..\..\Views\Configuration.cshtml"
               Write(Html.CheckBoxFor(m => m.DeviceReadyAlert));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    </div>\r\n</div>\r" +
"\n<script>\r\n    $(document).ready(function ()\r\n    {\r\n        $(\'<a>\').attr(\'href" +
"\', \'");

            
            #line 74 "..\..\Views\Configuration.cshtml"
                          Write(Plugin.ActionUrl("TestEmailConfiguration"));

            
            #line default
            #line hidden
WriteLiteral(@"').addClass('button').text('Send Test Email').prependTo('.actionBar');

        if ($('#AuthenticationRequried').not(':checked'))
        {
            $('#SmtpUsername').val("""");
            $('#SmtpPassword').val("""");
            $('#SmtpUsername').prop(""disabled"", !$(this).is(':checked'));
            $('#SmtpPassword').prop(""disabled"", !$(this).is(':checked'));
        }
    });

    $('#AuthenticationRequried').change(function() {
        $('#SmtpUsername').val("""");
        $('#SmtpPassword').val("""");
        $('#SmtpUsername').prop(""disabled"", !$(this).is(':checked'));
        $('#SmtpPassword').prop(""disabled"", !$(this).is(':checked'));
    });
</script>");

        }
    }
}
#pragma warning restore 1591
